#!/bin/bash 
#
# 1. To prepare: run 'dist' from sbt.
# 2. Run this script.
#
VERSION=`grep versionName appMain/build.gradle | awk '{gsub(/"/, "", $2); print $2}'`
TGT=../wrap/CarTLC/fdroid/repo
SRCFILE="./appMain/build/outputs/apk/debug/appMain-debug.apk"
SRCFILE2="./appMain/debug/appMain-debug.apk"
BUNDLE="./appMain/build/outputs/bundle/release/appMain-release.aab"
BUNDLE2="./appMain/release/appMain-release.aab"
RELEASE="./appMain/build/outputs/apk/release/appMain-release.apk"
RELEASE2="./appMain/release/appMain-release.apk"

while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
		-d)
                        if [ -f ${SRCFILE2} ]; then
                            echo -n "Ignored: "
                            ls -l $SRCFILE2
                        fi
			TGTFILE="CarTLC-d${VERSION}.apk"
                        shift # past argument
			;;
                -d2)
                        if [ -f ${SRCFILE} ]; then
                            echo -n "Ignored: "
                            ls -l $SRCFILE
                        fi
                        SRCFILE=${SRCFILE2}
			TGTFILE="CarTLC-d${VERSION}.apk"
                        shift # past argument
                        ;;
		-r)
			SRCFILE=`ls appMain/release/*.apk`
                        if [ -f ${RELEASE2} ]; then
                            echo -n "Ignored: "
                            ls -l $RELEASE2
                        fi
                        SRCFILE=${RELEASE}
			TGTFILE="CarTLC-r${VERSION}.apk"
                        shift # past argument
			;;
                -r2)
                        if [ -f ${RELEASE} ]; then
                            echo -n "Ignored: "
                            ls -l $RELEASE
                        fi
                        SRCFILE=${RELEASE2}
			TGTFILE="CarTLC-r${VERSION}.apk"
                        shift # past argument
                        ;;
                -b)
                        if [ -f ${BUNDLE2} ]; then
                            echo -n "Ignored: "
                            ls -l $BUNDLE2
                        fi
                        SRCFILE=${BUNDLE}
			TGTFILE="CarTLC-r${VERSION}.aab"
                        shift # past argument
                        ;;
                -b2)
                        if [ -f ${BUNDLE} ]; then
                            echo -n "Ignored: "
                            ls -l $BUNDLE
                        fi
                        SRCFILE=${BUNDLE2}
			TGTFILE="CarTLC-r${VERSION}.aab"
                        shift # past argument
                        ;;
		-clean)
			rm -f ${RELEASE} ${RELEASE2} ${SRCFILE} ${SRCFILE2} ${BUNDLE} ${BUNDLE2}
			echo "Removed files"
			exit 0
			;;

		*)
			print "Unknown opton: $key"
			exit 1;
			;;
	esac
done

echo -n "Using:   "
ls -l $SRCFILE

cp $SRCFILE $TGT/$TGTFILE
cp $SRCFILE ~/Downloads/$TGTFILE

echo "Created $TGTFILE and $TGT"
