#!/bin/bash 
#
# 1. To prepare: run 'dist' from sbt.
# 2. Run this script.
#
DATE=`date +%F`
VERSION=`grep versionName appMain/build.gradle | awk '{gsub(/"/, "", $2); print $2}'`
WRAP=../wrap/$DATE
TGT=~/Downloads

while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
		-d|--debug)
			SRCFILE="./appMain/build/outputs/apk/debug/appMain-debug.apk"
			TGTFILE="CarTLC-d${VERSION}.apk"
    		shift # past argument
    		;;
		-b)
			SRCFILE=`ls appMain/release/*.aab`
			TGTFILE="CarTLC-r${VERSION}.aab"
    		shift # past argument
    		;;
		-r)
			SRCFILE=`ls appMain/release/*.apk`
			TGTFILE="CarTLC-r${VERSION}.apk"
    		shift
		;;
		-clean)
			SRCFILE="./appMain/build/outputs/apk/debug/appMain-debug.apk"
			rm -f ${SRCFILE}
			SRCFILE=`ls appMain/release/*.aab`
			rm -f ${SRCFILE}
			SRCFILE=`ls appMain/release/*.apk`
			rm -f ${SRCFILE}
                        shift # past argument
			;;
		*)
			print "Unknown opton: $key"
			exit 1;
            # unknown option
		;;
	esac
done

mkdir -p $WRAP

ls $SRCFILE

cp $SRCFILE $WRAP/$TGTFILE
cp $WRAP/$TGTFILE $TGT/

echo "Created $TGTFILE in $WRAP and $TGT"
