#!/bin/bash 
#
# 1. To prepare: run 'dist' from sbt.
# 2. Run this script.
#
DATE=`date +%F`
WRAP=../wrap/$DATE
FILE=`ls server/play/target/universal/*.zip`
mkdir -p $WRAP
cp $FILE $WRAP/
echo "FOUND: $FILE"
COPY=`ls $WRAP/*.zip`

PEM=~/.ssh/FleetTLC.pem
SERVER="ubuntu@fleetdev.arqnetworks.com"

while [[ $# -gt 0 ]]
do
	key="$1"
	case $key in
		-r)
			SERVER="ubuntu@fleettlc.arqnetworks.com"
    		shift
    	;;
		-d)
			shift
		;;
		*)
			print "Unknown opton: $key"
			exit 1;
            # unknown option
		;;
	esac
done

echo "$SERVER:"
echo "$COPY"
ssh -i $PEM $SERVER mkdir -p server/$DATE
scp -i $PEM $COPY $SERVER:/home/ubuntu/server/$DATE
ssh -i $PEM $SERVER "cd server/$DATE; unzip *.zip"

echo "UPLOAD COMPLETE."
echo "Now on the server do this:"
echo " kill-server"
echo " cd ~/server; rm -f active; ln -s $DATE active; cd .."
echo " run-server"
