#!/bin/bash 
#
# Run this script directly on the machine 
#
kill-server
DATE=`date +%F`
FILE=`ls server/play/target/universal/*.zip`
TGT="~/server/$DATE"
mkdir -p $TGT
rm -f $TGT/*.zip
cp $FILE $TGT
cd $TGT
unzip *.zip
cd ~/server
rm -f active
ln -s $DATE active
echo "READY. Now do this:"
echo "run-server"
