#!/bin/bash 
#
# 1. To prepare: run 'dist' from sbt.
# 2. Run this script.
#
DATE=`date +%F`
VERSION=`grep versionName appMain/build.gradle | awk '{gsub(/"/, "", $2); print $2}'`
SRCFILE=`ls appMain/release/*.apk`
TGTFILE="CarTLC-r${VERSION}.apk"
WRAP=~/cartlc/wrap/$DATE
DROPBOX=~/Dropbox/Publish

while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
		-d|--debug)
			SRCFILE="./appMain/build/outputs/apk/debug/appMain-debug.apk"
			TGTFILE="CarTLC-d${VERSION}.apk"
    		shift # past argument
    	;;
		-r)
    		shift
		;;
		*)
			print "Unknown opton: $key"
			exit 1;
            # unknown option
		;;
	esac
done

mkdir -p $WRAP

ls $SRCFILE

cp $SRCFILE $WRAP/$TGTFILE
cp $WRAP/$TGTFILE $DROPBOX/

echo "Created $TGTFILE in $WRAP and $DROPBOX"
