#!/bin/bash 
#
# 1. To prepare: run 'dist' from sbt.
# 2. Run this script.
#
VERSION="0.1"
DATE=`date +%F`
WRAP=~/cartlc/wrap/$DATE
SRCFILE=`ls appMain/*.apk`
TGTFILE="CarTLC-r${VERSION}.apk"
mkdir -p $WRAP
cp $SRCFILE $WRAP/$TGTFILE
cp $WRAP/$TGTFILE ~/Dropbox/Publish/
