#!/bin/bash 
#
# 1. To prepare: run 'dist' from sbt.
# 2. Run this script.
#
VERSION="0.3"
DATE=`date +%F`
WRAP=~/cartlc/wrap/$DATE
SRCFILE="./appMain/build/outputs/apk/appMain-debug.apk"
TGTFILE="CarTLC-d${VERSION}.apk"
mkdir -p $WRAP
cp $SRCFILE $WRAP/$TGTFILE
cp $WRAP/$TGTFILE ~/Dropbox/Publish/
