#!/bin/bash 
#
# 1. To prepare: run 'dist' from sbt.
# 2. Run this script.
#
DATE=`date +%F`
WRAP=~/cartlc/wrap/$DATE
FILE=`ls play-ebean/target/universal/*.zip`
mkdir -p $WRAP
cp $FILE $WRAP/

COPY=`ls $WRAP/*.zip`

ssh -i ~/.ssh/cartlc.pem ubuntu@cartlc.arqnetworks.com mkdir -p server/$DATE
scp -i ~/.ssh/cartlc.pem $COPY ubuntu@cartlc.arqnetworks.com:/home/ubuntu/server/$DATE

echo "Then on the server do this:"
echo "unzip server/$DATE/*.zip"
echo "run-server &"
