#!/bin/bash 
#
# 1. To prepare: run 'dist' from sbt.
# 2. Run this script.
#
WRAP=~/cartlc/wrap/`date +%F`
FILE=`ls play-ebean/target/universal/*.zip`
mkdir -p $WRAP
cp $FILE $WRAP/

COPY=`ls $WRAP/*.zip`

echo "Run this command:"
echo "scp -i ~/.ssh/cartlc.pem $COPY ubuntu@cartlc.arqnetworks.com:/home/ubuntu/server/"
echo "Then on the server do this:"
echo "run-server &"
