#!/bin/bash
# 
# This script is expected to be called from crontab with the entry:
#
# @reboot ubuntu /home/ubuntu/bin/run_server
#
H=/home/ubuntu
ACTIVE=$H/server/active/play*/bin/play
LOG=$H/logs/run-`date +%Y-%m-%d`.log
mkdir -p $H/logs
$ACTIVE -J-Xms1024M -J-Xmx4000m -Dhttps.port=9443 -Dplay.evolutions.db.default.autoApply=true -Dplay.evolutions.db.default.autoApplyDowns=true -Dplay -Dplay.http.secret.key='${APPLICATION_SECRET}' >& $LOG &
