#!/bin/bash
# crontab -e
# Add:
# @weekly ubuntu /home/ubuntu/bin/run-backup
H=/home/ubuntu
cd $H/backup
FILE=dump-`date +%Y-%m-%d`.sql
mysqldump --databases cartlc -u cartlc --password=cartcl > $FILE
chmod 444 $FILE
