#!/bin/bash
# 
# This script is expected to be called from crontab with the entry:
#
# @reboot ubuntu /home/ubuntu/bin/run_server
#
H=/home/ubuntu
ACTIVE=$H/server/active/play*SNAPSHOT/bin/play
LOG=$H/bin/logs/run.log
mkdir -p $H/bin/logs
$ACTIVE -Dplay.evolutions.db.default.autoApply=true -Dplay.evolutions.db.default.autoApplyDowns=true -Dplay -Dplay.crypto.secret='${APPLICATION_SECRET}' >& $LOG &
